--- #YAML:1.0
name:                Blitz
version:             0.01
abstract:            Perl module for API access to Blitz
license:             perl
author:              
    - Ben Klaas <ben@benklaas.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    JSON::XS:                      2.3
    LWP:                           0
    MIME::Base64:                  0
    Regexp::Common:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
